name: run pytest -v

on: # when to run
  push:
    branches: [main]
  
  pull_request:
    branches: [main]

jobs:

  #build:
    # build steps here

  test: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.7, 3.9]

    steps:

      - name: checkout repository content
        uses: actions/checkout@v2 # use pre-existing action

      - name: setup python
        uses: actions/setup-python@v4 # details: https://github.com/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |  # indicates terminal commands
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: run tests
        run: |
          pytest -v

  #deploy:
    # deploy steps here
          